version: "3.9"
services:
  nginx:
    build: ./infrastructure/nginx/base
    image: jakmall/recruitment/cloud-engineer/counter/nginx
    environment:
      FASTCGI_PASS: php-fpm:9000
    volumes:
      - ./src/public:/var/www/html/public
    ports:
      - ${DOCKER_COMPOSE_NGINX_HOST_PORT}:80